from app.schemas.llamada import (
    LlamadaBase, 
    LlamadaProximaResponse, 
    LlamadaNoDisponibleResponse, 
    ErrorResponse, 
    FinalizarLlamadaRequest, 
    FinalizarLlamadaResponse
)
from app.schemas.usuario import UsuarioBase, UsuarioCreate, Usuario, UsuarioInDB
from app.schemas.estadisticas import EstadisticasLlamadasResponse
from app.schemas.webhook import WebhookLlamadaRequest, WebhookLlamadaResponse, WebhookErrorResponse
from app.schemas.lista_llamadas import (
    ListaLlamadasBase,
    ListaLlamadasCreate,
    ListaLlamadasUpdate,
    ListaLlamadasResponse,
    ListaLlamadasDetailResponse,
    NumeroLlamadaBase,
    NumeroLlamadaCreate,
    NumeroLlamadaResponse,
    UploadArchivoResponse,
    ValidacionNumero,
    validar_numero_telefone,
    normalizar_numero_argentino
)
from app.schemas.blacklist import (
    BlacklistBase,
    BlacklistCreate,
    BlacklistUpdate,
    BlacklistResponse,
    BlacklistVerificationRequest,
    BlacklistVerificationResponse,
    BlacklistBulkAddRequest,
    BlacklistBulkAddResponse,
    BlacklistStatsResponse,
    BlacklistSearchRequest
)
from app.schemas.cli import (
    CliBase,
    CliCreate,
    CliUpdate,
    CliResponse,
    CliBulkAddRequest,
    CliBulkAddResponse,
    CliStatsResponse,
    CliRandomRequest,
    CliRandomResponse
)
# from app.schemas.presione1 import (
#     CampanaPresione1Base,
#     CampanaPresione1Create,
#     CampanaPresione1Update,
#     CampanaPresione1Response,
#     LlamadaPresione1Base,
#     LlamadaPresione1Response,
#     IniciarCampanaRequest,
#     PausarCampanaRequest,
#     EstadisticasCampanaResponse,
#     MonitorCampanaResponse
# )

__all__ = [
    'LlamadaBase',
    'LlamadaProximaResponse',
    'LlamadaNoDisponibleResponse',
    'ErrorResponse',
    'FinalizarLlamadaRequest',
    'FinalizarLlamadaResponse',
    'UsuarioBase',
    'UsuarioCreate',
    'Usuario',
    'UsuarioInDB',
    'EstadisticasLlamadasResponse',
    'WebhookLlamadaRequest',
    'WebhookLlamadaResponse',
    'WebhookErrorResponse',
    'ListaLlamadasBase',
    'ListaLlamadasCreate',
    'ListaLlamadasUpdate',
    'ListaLlamadasResponse',
    'ListaLlamadasDetailResponse',
    'NumeroLlamadaBase',
    'NumeroLlamadaCreate',
    'NumeroLlamadaResponse',
    'UploadArchivoResponse',
    'ValidacionNumero',
    'validar_numero_telefone',
    'normalizar_numero_argentino',
    'BlacklistBase',
    'BlacklistCreate',
    'BlacklistUpdate',
    'BlacklistResponse',
    'BlacklistVerificationRequest',
    'BlacklistVerificationResponse',
    'BlacklistBulkAddRequest',
    'BlacklistBulkAddResponse',
    'BlacklistStatsResponse',
    'BlacklistSearchRequest',
    'CliBase',
    'CliCreate',
    'CliUpdate',
    'CliResponse',
    'CliBulkAddRequest',
    'CliBulkAddResponse',
    'CliStatsResponse',
    'CliRandomRequest',
    'CliRandomResponse',
    # 'CampanaPresione1Base',
    # 'CampanaPresione1Create',
    # 'CampanaPresione1Update',
    # 'CampanaPresione1Response',
    # 'LlamadaPresione1Base',
    # 'LlamadaPresione1Response',
    # 'IniciarCampanaRequest',
    # 'PausarCampanaRequest',
    # 'EstadisticasCampanaResponse',
    # 'MonitorCampanaResponse'
] 
